apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-app
  labels:
    name: cncf-webapp-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cncfweb
  template:
    metadata:
      labels:
        app: cncfweb
    spec:
      containers:
      - name: cncfweb-app
        image: cncfid2022.azurecr.io/cncf/id/2022/workshop/cncfworkshopweb:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"